### ISSUE TITLE
Virtual Entity and Digital Entity Alignment with IoT RA

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-core#11]
IoT RA distinguishes between Digital entity and Virtual entity. We have Virtual entity inherited from WoT. Shall we include the Digital entity in the core model to align it more with IoT or is it not needed?

**Comment by fserena** [comment]
Is there any property that could distinguish them? If not, I would keep the Virtual entity concept.

**Comment by rgcmme** [comment]
Do we need the Digital entity for something? If not, we don't need to create it; maybe we can state in the documentation that the RA also defines Digital entities.

**Comment by mariapoveda** [comment]
We already have this comment which mentions the digital entity. 

"A virtual entity is a digital representation of a physical entity, contained within a service. A virtual entity interacts through an endpoint. A virtual entity represents a physical entity.
(Definition taken from  ISO/IEC CC 30141. Information technology - Internet of Things Reference architecutre (IoT RA))"

I close this issue.
