### ISSUE TITLE
A web thing core:contains other web things

### ISSUE THREAD

**Issue by fserena** [mariapoveda/vicinity-ontology-core#33]
A new predicate is required to represent physical containment for core:PhysicalThing.

**Comment by mariapoveda** [comment]
Right now we follow the ISO RA. We agreed to postpone this decision until we have clear requirements about this.

**Comment by rgcmme** [comment]
In SSN, systems have subsystems. Maybe this can be used, although not every PhysicalThing is a System...
Maybe we need an upper level containment property.

**Comment by fserena** [comment]
I think we should try to avoid weird situations like "a thermometer contains a weather station". However, the opposite seems OK. As @rgcmme proposes, including "Systems" and subproperties of core:contains can be a good solution.

**Comment by mariapoveda** [comment]
After a meeting we decided to remove core:contains and create a class ComposedThing and the properties core:isComposedBy and core:exposes. 
Virtual things can only be composed by virtual things. No restriction for PhysicalThings.
