### ISSUE TITLE
Observable and actuatable properties

### ISSUE THREAD

**Issue by rgcmme** [mariapoveda/vicinity-ontology-core#41]
SOSA distinguishes among observable and actuatable properties.

We should classify our properties in one of the two groups (or in both if necessary).

**Comment by mariapoveda** [comment]
I have my doubts about the accuracy of doing it manually.

.- It will has to be done every time a property is added
.- It could be difficult to determine which property is actuable or not. Many opinions might arise.
.- Would it be possible that a property become actuable with time?

What if we include an equivalentClass local axiom for actuable and observable properties in the core module if they are object of the properties sosa:actsOnProperty and sosa:observes respectively? 

We can also do both things. Define as observable or actuable all the properties we have for now and also include the axioms.

**Comment by rgcmme** [comment]
Yes, it has to be done manually every time a property is included, but this is logical.

A property may be both observable and actuatable. 

Right now I think that we only have observable properties. We can define all of them as observable (unless we see some that are clearly actuatable) and later if needed also define them as actuatable.

**Comment by mariapoveda** [comment]
I'll review them a propose a list of actuable ones. Agree that all of them are observable.

**Comment by mariapoveda** [comment]
Proposal for actuable properties:

- core:RelativeHumidity
- core:AmbientTemperature
- core:DeviceTemperature
- core:MeatProbeTemperature
- core:BakeRemainingTime
- core:ElapsedBakingTime
- core:Luminance
- core:LightColor

**Comment by rgcmme** [comment]
Will there be any device that allows changing the humidity of a place or the ambient temperature? Or the remaining times of the oven? I don't think so.

I see it clearly for the Device(Oven)Temperature, the luminance and the light color. But only for those.

**Comment by mariapoveda** [comment]
Fixed.
