### ISSUE TITLE
Is it necessary to import the whole SSN?

### ISSUE THREAD

**Issue by rgcmme** [mariapoveda/vicinity-ontology-core#44]
Importing all the ontology includes all the vocabulary terms, even those that are not used in VICINITY.
Furthermore, it also includes deprecated properties (e.g., SensingDevice).

**Comment by mariapoveda** [comment]
I think it is convenience to not reproduce everything that you need and include all the local axioms. Even though the cost is adding somethings that are not needed, but that does not harm.   

SensingDevice is referenced in core and marked as deprecated for backwards compatibility as it is not imported by the new ssn.

**Comment by rgcmme** [comment]
Then I propose to leave only the things that we are using.
And to remove SensingDevice, since our user base is not so broad right now.

**Comment by mariapoveda** [comment]
ok. 

What about importing only SOSA? I think it is worth having one statement than extracting all the reused elements.

**Comment by rgcmme** [comment]
May be an option. We will be including things out of our scope such as actuators and samplers, but at least it is better than importing the whole ssn.
