### ISSUE TITLE
Device as subclass of ssn:System

### ISSUE THREAD

**Issue by rgcmme** [mariapoveda/vicinity-ontology-core#45]
Device should be represented as a subclass of ssn:System. 

If not, it won't appear in the systems hierarchy and it should be because every device is a system.

**Comment by mariapoveda** [comment]
added core:Device rdfs:subclassOf ssn:System

**Comment by rgcmme** [comment]
Yes, according to the official definition in SSN: "System is a unit of abstraction for pieces of infrastructure that implement Procedures. A System may have components, its subsystems, which are other Systems."
