### ISSUE TITLE
Does TED belong to this domain?

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-core#5]
@fserena I'd like to make sure whether TEDs will be used as VICINITY and therefore it belongs to the core ontology or they would be only used in the WoT mappings ontology.

**Comment by fserena** [comment]
TEDs represent ecosystems of things (aggregation of resources), which are very related to VICINITY, but not exclusively... so for now I would include it in the wot-mappings ontology.

**Comment by mariapoveda** [comment]
It is in the VICNITY core until we have a new name or final decision about it.

**Comment by rgcmme** [comment]
Right now both thing ecosystems and their descriptions are in the core ontology; we can close this issue.
