### ISSUE TITLE
Decoupling core:VirtualThing y core:PhysicalThing from wot:Thing

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-core#67]
core:VirtualThing and core:PhysicalThing should have a domain relation to wot:Thing instead of subclassOf. The wot:Thing(s) define web representation of the things, therefore have a different nature.

core:hasWebRepresentation and its inverse core:isWebRepresentation of are suggested. Any other idea @rgcmme ?

**Comment by rgcmme** [comment]
I agree with the change.
And also don't have a better idea for the name. Maybe we can check how is the relationship named in other places.

**Comment by mariapoveda** [comment]
From ISO/IEC Internet of Things Reference Architecture (IoT RA):

- VirtualEntity-represents-PhysicalEntity -> However we would still have VitualEntity for services that should be linked to wot:Thing
- IoTDevice-exposes-Endpoint and Service-exposes-Endpoint -> this option could be more aligned in the sense that we need to link devices (and its parent class PhysicalThing) and services (and its parent class VirtualThing) to wot:Thing which will include a link to the endpoint in which the thing is exposed.

I would also rename VirtualThing and PhysicalThing to VirtualEntity and PhysicalEntity in line with IoT-RA.

**Comment by mariapoveda** [comment]
core:VirtualThing, core:PhysicalThing and core:ComposedThing classes will be direct subclass of owl:Thing.

A new pair of relationships core:represents and core:isRepresentedBy are will hold between wot:Thing and owl:Thing

The property core:isComposedBy range will be uptadet to owl:Thing
