### ISSUE TITLE
ssn:Property

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-core#8]
In the IoT RA the devices monitor physical entities and actuators act on physical entities.
Would we like to include the possibility of monitor/act over Properties of the entities following the SSN pattern?

@fserena
@rgcmme

**Comment by rgcmme** [comment]
I think so. Let's try an approach that is compatible with both views.

**Comment by mariapoveda** [comment]
Added in the ontology in the form of local constrains
