### ISSUE TITLE
Contract definition

### ISSUE THREAD

**Issue by Joralmi** [mariapoveda/vicinity-ontology-core#80]
#### A contract in the NM contains the following elements:
* ctid: <Identifier to be used everywhere>
* foreignIot: <Object containing ids of the users, items and organisations owner of the service>
* iotOwner: <Object containing ids of the users, items and organisations requesting the service>
* readWrite: Boolean // True RW -- False R
* legalDescription: <Legal text describing the actual contract>
* Other flags and properties necessary for the NM.

#### My suggestion for the semantic repository
It would probably be enough storing the ids of the **organisations** and **items** that are part of the contract.
The contract does not even need to know to which organisation the item belongs, because that would be stored under the organisation class.
Of course the ctid (same as oid for objects) needs to be placed as an identifier.

**Comment by mariapoveda** [comment]
Do the contract only involve organisations in one side and services in the other or could it be also between organisations and devices?

**Comment by mariapoveda** [comment]
Are the foreignIoT and iotOwner description swapped?

**Comment by mariapoveda** [comment]
@Joralmi  Some questions to be solved:

- Do the contract only involve organisations in one side and services in the other or could it be also between organisations and devices?
- whether the involved services should be only 1 or could be more.
- Are the foreignIoT and iotOwner description swapped?

For the moment see the proposed modelling for the contracts. Does it fit the needs?

[contractModelv1.pdf](https://github.com/mariapoveda/vicinity-ontology-core/files/2786836/contractModelv1.pdf)
