### ISSUE TITLE
Building definition

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [mariapoveda/vicinity-ontology-core#81]
We would like to include saref to model building and administrative areas.
Cheers

**Comment by mariapoveda** [comment]
See the proposal model attached. Does it cover the needs @AndreaCimminoArriaga ?
![proposalbuildingsv1](https://user-images.githubusercontent.com/5693576/51626078-093e7680-1f3f-11e9-8747-31a5a67ca6a9.png)

**Comment by mariapoveda** [comment]
@AndreaCimminoArriaga  see the proposal for modelling the location of devices (generalized as physical things). Does it cover the needs?
![proposalbuildingsv1](https://user-images.githubusercontent.com/5693576/51626209-4e62a880-1f3f-11e9-97fa-a2869289d966.png)

**Comment by AndreaCimminoArriaga** [comment]
Yes, I think this will work fine. Thank you
